pipeline {
    agent any

	environment {
		CMAKE_BUILD_TYPE=Release
		CMAKE_SYSTEM_PREFIX_PATH=install
		MAKE_THREADS=4
	}

    stages {
        stage('Build') {
            steps {			
				sh 'cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${CMAKE_SYSTEM_PREFIX_PATH}/mpo ..'
				# sh 'make -j ${MAKE_THREADS}'
            }
        }
    }
}

